// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'fr'

export type Locales =
	| 'en'
	| 'fr'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * B​o​n​j​o​u​r​ ​{​n​a​m​e​}​!​ ​M​e​r​c​i​ ​d​e​ ​m​e​t​t​r​e​ ​u​n​e​ ​é​t​o​i​l​e​ ​s​i​ ​v​o​u​s​ ​a​i​m​e​z​ ​c​e​ ​p​r​o​j​e​t
	 * @param {unknown} name
	 */
	hi: RequiredParams<'name'>
	/**
	 * R​e​c​h​e​r​c​h​e​r
	 */
	search: string
}

export type TranslationFunctions = {
	/**
	 * Bonjour {name}! Merci de mettre une étoile si vous aimez ce projet
	 */
	hi: (arg: { name: unknown }) => LocalizedString
	/**
	 * Rechercher
	 */
	search: () => LocalizedString
}

export type Formatters = {}
